### ISSUE TITLE
Is it possible to also deform points with some coordinates?

### ISSUE THREAD

**Issue by koegl** [gvtulder/elasticdeform#15]
I'm working on image registration, where I have a moving image that I want to register to a fixed image.

Both images have a set of corresponding landmarks, that I need to use to evaluate the quality of the registration.

To do this, I need to deform the moving image and the corresponding landmarks with the same deformation field.

Is there a way to use Elasticdeform to deform a set of landmarks (i.e. points with some coordinates)?

**Comment by gvtulder** [comment]
No, there's currently no function to transform landmarks directly.
* You could plot the landmarks as points in a binary image, apply the deformation with `order=0`, and look at the results. That would at least give you a visual confirmation.
* You could also have a look at the Python implementation that is used for the tests: https://github.com/gvtulder/elasticdeform/blob/master/test_deform_grid.py#L26-L62

  That function computes the coordinates map for the output image. For example, `coordinates[10, 13] = [9, 12]` would mean that pixel (10, 13) in the output is based on pixel (9, 12) of the input.

  In a sense, it's the opposite of what you want: if you know where the landmark is in the output, you can look up where it was in the input. You might be able to use this in reverse, but I don't know if that also works for your application.
