### ISSUE TITLE
ModuleNotFoundError: No module named 'elasticdeform.torch'

### ISSUE THREAD

**Issue by HilbertMaximov** [gvtulder/elasticdeform#18]
When I 'import elasticdeform.torch as etorch', it says: ModuleNotFoundError: No module named 'elasticdeform.torch', my elasticdeform version is 0.4.7, could you help me with this?
Thank you very much!

**Comment by gvtulder** [comment]
That's strange. It might be an installation issue. Did you install the pip package or are you running this from git?

Can you import the package without elasticdeform? For example, does this give an error?
```python
import elasticdeform
print(elasticdeform.deform_grid)
```

I tried to reproduce this in a clean virtual environment, but that doesn't give me any errors. Perhaps you could try that on your system?

* initialize a new virtual environment
* run `pip install elasticdeform` and `pip install torch`
* then `import elasticdeform.torch`

I'd be curious to hear how that works for you.
