### ISSUE TITLE
There is a bug while installing by pip

### ISSUE THREAD

**Issue by qsyao** [gvtulder/elasticdeform#2]
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Collecting git+https://github.com/gvtulder/elasticdeform
  Cloning https://github.com/gvtulder/elasticdeform to /tmp/pip-req-build-gw9pip3y
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gw9pip3y/setup.py", line 13, in <module>
        readme_txt = f.read()
      File "/home/chuang/torvnet/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 601: ordinal not in range(128)

**Comment by gvtulder** [comment]
Thanks for the bug report. I don't have any problems on my system (it might depend on your local character encoding settings). I've removed the non-ASCII characters from the readme. Could you try again?

**Comment by qsyao** [comment]
with open("README.md", encoding='utf-8') can fix this problem :) .  Thanks for this good tool!

**Comment by gvtulder** [comment]
Yes, that's indeed a better solution. Thanks!
