### ISSUE TITLE
pip installation fails on Mac OSX Mojave 10.14.2

### ISSUE THREAD

**Issue by tuttoweb** [gvtulder/elasticdeform#3]
Hello,
I am trying to install this library on my Mac.
There is a problem with the build_ext

`$ pip install elasticdeform
Collecting elasticdeform
  Using cached https://files.pythonhosted.org/packages/35/bf/0c44af3eb721d492162a148c8b9de947fa3e16befeaaf57ebe1e50970482/elasticdeform-0.4.4.tar.gz
Requirement already satisfied: numpy in /Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages (from elasticdeform) (1.16.1)
Requirement already satisfied: scipy in /Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages (from elasticdeform) (1.2.1)
Building wheels for collected packages: elasticdeform
  Building wheel for elasticdeform (setup.py) ... error
  Complete output from command /Users/tuttoweb/miniconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zg/z3fmkq010jd97lyxpr0v8bw00000gn/T/pip-install-73szftka/elasticdeform/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/zg/z3fmkq010jd97lyxpr0v8bw00000gn/T/pip-wheel-lrzf2jhr --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.5-x86_64-3.5
  creating build/lib.macosx-10.5-x86_64-3.5/elasticdeform
  copying elasticdeform/tf.py -> build/lib.macosx-10.5-x86_64-3.5/elasticdeform
  copying elasticdeform/__init__.py -> build/lib.macosx-10.5-x86_64-3.5/elasticdeform
  copying elasticdeform/deform_grid.py -> build/lib.macosx-10.5-x86_64-3.5/elasticdeform
  running build_ext
  building 'elasticdeform._deform_grid' extension
  creating build/temp.macosx-10.5-x86_64-3.5
  creating build/temp.macosx-10.5-x86_64-3.5/elasticdeform
  gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tuttoweb/miniconda2/envs/py3/include -arch x86_64 -Ielasticdeform -I/Users/tuttoweb/miniconda2/envs/py3/include/python3.5m -I/Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages/numpy/core/include -c elasticdeform/_deform_grid.c -o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/_deform_grid.o
  gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tuttoweb/miniconda2/envs/py3/include -arch x86_64 -Ielasticdeform -I/Users/tuttoweb/miniconda2/envs/py3/include/python3.5m -I/Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages/numpy/core/include -c elasticdeform/deform.c -o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/deform.o
  gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tuttoweb/miniconda2/envs/py3/include -arch x86_64 -Ielasticdeform -I/Users/tuttoweb/miniconda2/envs/py3/include/python3.5m -I/Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages/numpy/core/include -c elasticdeform/from_nd_image.c -o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/from_nd_image.o
  gcc -bundle -undefined dynamic_lookup -L/Users/tuttoweb/miniconda2/envs/py3/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.5/elasticdeform/_deform_grid.o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/deform.o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/from_nd_image.o -L/Users/tuttoweb/miniconda2/envs/py3/lib -o build/lib.macosx-10.5-x86_64-3.5/elasticdeform/_deform_grid.cpython-35m-darwin.so
  ld: library not found for -lgcc_s.10.5
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for elasticdeform
  Running setup.py clean for elasticdeform
Failed to build elasticdeform
Installing collected packages: elasticdeform
  Running setup.py install for elasticdeform ... error
    Complete output from command /Users/tuttoweb/miniconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zg/z3fmkq010jd97lyxpr0v8bw00000gn/T/pip-install-73szftka/elasticdeform/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/zg/z3fmkq010jd97lyxpr0v8bw00000gn/T/pip-record-pb87xfgh/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.5-x86_64-3.5
    creating build/lib.macosx-10.5-x86_64-3.5/elasticdeform
    copying elasticdeform/tf.py -> build/lib.macosx-10.5-x86_64-3.5/elasticdeform
    copying elasticdeform/__init__.py -> build/lib.macosx-10.5-x86_64-3.5/elasticdeform
    copying elasticdeform/deform_grid.py -> build/lib.macosx-10.5-x86_64-3.5/elasticdeform
    running build_ext
    building 'elasticdeform._deform_grid' extension
    creating build/temp.macosx-10.5-x86_64-3.5
    creating build/temp.macosx-10.5-x86_64-3.5/elasticdeform
    gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tuttoweb/miniconda2/envs/py3/include -arch x86_64 -Ielasticdeform -I/Users/tuttoweb/miniconda2/envs/py3/include/python3.5m -I/Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages/numpy/core/include -c elasticdeform/_deform_grid.c -o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/_deform_grid.o
    gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tuttoweb/miniconda2/envs/py3/include -arch x86_64 -Ielasticdeform -I/Users/tuttoweb/miniconda2/envs/py3/include/python3.5m -I/Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages/numpy/core/include -c elasticdeform/deform.c -o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/deform.o
    gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tuttoweb/miniconda2/envs/py3/include -arch x86_64 -Ielasticdeform -I/Users/tuttoweb/miniconda2/envs/py3/include/python3.5m -I/Users/tuttoweb/miniconda2/envs/py3/lib/python3.5/site-packages/numpy/core/include -c elasticdeform/from_nd_image.c -o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/from_nd_image.o
    gcc -bundle -undefined dynamic_lookup -L/Users/tuttoweb/miniconda2/envs/py3/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.5/elasticdeform/_deform_grid.o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/deform.o build/temp.macosx-10.5-x86_64-3.5/elasticdeform/from_nd_image.o -L/Users/tuttoweb/miniconda2/envs/py3/lib -o build/lib.macosx-10.5-x86_64-3.5/elasticdeform/_deform_grid.cpython-35m-darwin.so
    ld: library not found for -lgcc_s.10.5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/tuttoweb/miniconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zg/z3fmkq010jd97lyxpr0v8bw00000gn/T/pip-install-73szftka/elasticdeform/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/zg/z3fmkq010jd97lyxpr0v8bw00000gn/T/pip-record-pb87xfgh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/zg/z3fmkq010jd97lyxpr0v8bw00000gn/T/pip-install-73szftka/elasticdeform/
`

I am using python 3.4 installed with anaconda. I also tried to download the git and install from there, but I get the same error. In my system, there is the gcc library libgcc_s.1.dylib, but I don't know whether to get the required one. I googled it without success.

Thanks a lot for your support

**Comment by gvtulder** [comment]
Thanks for the report. I don't use a Mac, so I can't check, but people seem to suggest that updating your Xcode helps. Have you tried that already? Apparently there's Xcode and Command line tool that you can update. (See, e.g., https://github.com/BelledonneCommunications/linphone-iphone/issues/257#issuecomment-311629320.)

It's possible that there's also something that needs to be changed in the package, but I wouldn't immediately know what it should be.

**Comment by tuttoweb** [comment]
Thanks for your prompt reply, gvtulder.
I had checked my Xcode version and I thought it was fine. I am still getting this unpleasant error. I managed to install the library successfully on a linux machine using pip.

In case you came across to any updates, please let me know.
