### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by pdelgado248** [gvtulder/elasticdeform#9]
Hello,

I was using the code 4 days ago in Google Colab and everything worked smoothly, but just as I tried it today, even in a totally empty notebook with just these lines:

_!pip install elasticdeform
import elasticdeform_

it throws an error that it didn't earlier. 

![image](https://user-images.githubusercontent.com/22975769/109483603-c1746c80-7a7f-11eb-9066-814ad64e0a8b.png)

Is there any problem now with previously used numpy versions? Has something changed regarding this? Even trying the previous 0.4.7 version throws the same error now, and as far as I know that was the one I used previously without any problems.

Thank you for your help

**Comment by gvtulder** [comment]
Thanks for letting me know. This is a problem I created by uploading pre-build binary packages for the latest version. As these were built with the newest NumPy version, they wouldn't work for older versions, such as the one preinstalled on Google Colab.

I'm not sure why reinstalling 0.4.7 didn't work. That only has source packages, so it should still work. Are you sure you restarted your notebook when you tried that?

I've rebuilt the packages with earlier NumPy versions (see elasticdeform v0.4.9), so if you upgrade the elasticdeform package it should now work better. It works for me on Google Colab, but let me know if it still doesn't work for you.

**Comment by pdelgado248** [comment]
Thank you very much for your quick response, now 

_!pip install elasticdeform
import elasticdeform_

works without any issues.  I am not sure what the error was due to when using previous versions, but I probably made some mistake in between. The new version works well now, so that's perfect.
